// src/components/LatestBlogPosts/LatestBlogPosts.tsx
import React from "react";
import { graphql, StaticQuery } from "gatsby";
import styled from "styled-components";
import { Button } from "@adamwebster/fused-components";
import LatestBlogPost from "./LatestBlogPost";

const StyledLatestBlogPostsSection = styled.section`
  display: flex;
  width: 100%;
  margin-bottom: 60px;
  box-sizing: border-box;
  flex-flow: column;
  border-bottom: solid 1px var(--border-color);
  padding-bottom: 30px;
  @media only screen and (max-width: 768px) {
    display: block;
  }
`;

const StyledLatestBlogPostsSectionInner = styled.div`
  flex-flow: row;
  display: flex;
  h1 {
    font-size: 40px;
    line-height: 1;
    margin: 0;
    font-weight: 300;
    text-transform: uppercase;
  }
  @media only screen and (max-width: 600px) {
    flex-flow: column-reverse;
  }
`;

const StyledLatestBlogItems = styled.div`
  margin-right: 30px;
  flex: 1 1;
  display: grid;
  grid-template-rows: 1fr;
  grid-template-columns: 1fr 1fr 1fr;
  grid-gap: 20px;
  @media only screen and (max-width: 768px) {
    display: block;
  }
  @media only screen and (max-width: 600px) {
    margin-top: 20px;
    margin-left: 0;
    margin-right: 0;
  }
`;

const StyledListMore = styled.div`
  display: flex;
  align-content: center;
  justify-content: center;
  padding: 20px;
`;
const LatestBlogPosts = () => {
  return (
    <StaticQuery
      query={graphql`
        query {
          allMdx(
            limit: 4
            filter: { fields: { sourceInstanceName: { eq: "blog-post" } } }
          ) {
            edges {
              node {
                id
                frontmatter {
                  title
                  date
                  path
                  featuredImage {
                    childImageSharp {
                      fluid(maxWidth: 800) {
                        ...GatsbyImageSharpFluid
                      }
                    }
                  }
                }
                body
                excerpt
              }
            }
          }
        }
      `}
      render={({ allMdx: { edges } }) => {
        return (
          <>
            <StyledLatestBlogPostsSection id="LatestBlogPosts">
              <StyledLatestBlogPostsSectionInner>
                <StyledLatestBlogItems>
                  {edges.map(({ node }: any) => {
                    return <LatestBlogPost node={node} />;
                  })}
                </StyledLatestBlogItems>
                <div>
                  <h1>
                    Latest Blog
                    <br />
                    Posts
                  </h1>
                </div>
              </StyledLatestBlogPostsSectionInner>
              <StyledListMore>
                <Button primary>Read More</Button>{" "}
              </StyledListMore>
            </StyledLatestBlogPostsSection>
          </>
        );
      }}
    />
  );
};

export default LatestBlogPosts;

// src/components/LatestBlogPosts/LatestBlogPosts.svelte
<script>
  import Button from "../Button/Button.svelte";
  import BlogPost from "./BlogPost.svelte";
  const HandleClick = () => {
    alert("click");
  };
</script>

<style>
  h1 {
    font-size: 40px;
    line-height: 1;
    margin: 0;
    font-weight: 300;
    text-transform: uppercase;
  }
  .awm-section-wrapper {
    display: flex;
    width: 100%;
    margin-bottom: 60px;
    box-sizing: border-box;
    flex-flow: column;
  }
  .awm-section-inner {
    flex-flow: row;
    display: flex;
  }
  .awm-list-of-posts {
    margin-right: 30px;
    flex: 1 1;
    display: grid;
    grid-template-rows: 1fr;
    grid-template-columns: 1fr 1fr 1fr;
    grid-gap: 20px;
  }
  .awm-list-more {
    display: flex;
    align-content: center;
    justify-content: center;
    padding: 20px;
  }

  @media only screen and (max-width: 768px) {
    .awm-list-of-posts,
    .awm-section-wrapper {
      
     display: block;
    }
  }
  @media only screen and (max-width: 600px) {
    .awm-list-of-posts {
      margin-top: 20px;
      margin-left: 0;
      margin-right: 0;
    }
    .awm-section-inner {
      flex-flow: column-reverse;
    }
  }
</style>

<section class="awm-section-wrapper" id="LatestBlogPosts">
  <div class="awm-section-inner">
    <div class="awm-list-of-posts">
      <BlogPost />
      <BlogPost />
      <BlogPost />
    </div>
    <div>
      <h1>
        Latest Blog
        <br />
        Posts
      </h1>
    </div>
  </div>
  <div class="awm-list-more">
    <Button primary on:click={HandleClick}>Read More</Button>
  </div>
</section>
